package tracing

import (
	"strings"
	"time"

	"poc/commons/core/constants"
)

type AutoGeneratedParam string

const (
	TIMESTAMP AutoGeneratedParam = "TIMESTAMP"
)

const defaultDatePattern = "20060102150405.000"

func (param AutoGeneratedParam) Generate() string {
	switch param {
	case TIMESTAMP:
		s := time.Now().Format(defaultDatePattern)
		return strings.ReplaceAll(s, constants.DOT, constants.EMPTY)
	default:
		return constants.EMPTY
	}
}
