name: payment-v1
image:
  repository: miguelarmasabt/payment
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8015
  nodePort: 30015
replicas: 1

configMaps:
  CONFIG_SERVER_DOMAIN: "config-server-v1:8888"
  MYSQL_DOMAIN: "mysql-db:3306"
  MYSQL_USERNAME: "poc_user"
  KAFKA_DOMAIN: "kafka-server:9093"
  CREATE_TOPICS: "true"
  JAVA_OPTS: "-Xms256M -Xmx256M"

secrets:
  MYSQL_PASSWORD: "qwerty"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8015
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8015
  initialDelaySeconds: 60
  periodSeconds: 30

namespace: restaurant
helmTemplate: with-health

docker:
  hostPort: 8015
  dependencies: config-server-v1;mysql-db;kafka-server
  volumes: none