name: keycloak-server

container:
  image:
    repository: quay.io/keycloak/keycloak
    tag: "16.0.0"
    pullPolicy: IfNotPresent
  port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"

configMaps:
  KEYCLOAK_USER: "admin"
  DB_VENDOR: "H2"

secrets:
  KEYCLOAK_PASSWORD: "admin"

service:
  nodePort: 30180

deployment:
  replicas: 1

hpa:
  enabled: false

namespace: restaurant
helmTemplate: default

docker:
  hostPort: 8091
  dependencies: none
  volumes: none