pipeline {
    agent any
    stages {
        stage('Deploy') {
            steps {
                withCredentials(bindings: [ string(credentialsId: 'k8s-cluster-token', variable: 'api_token') ]) {
                    sh 'kubectl apply -f devops/k8s-manifests/redis-server.yaml --server https://d244-179-6-4-43.ngrok-free.app --token $api_token --insecure-skip-tls-verify=true'
                }
            }
        }
    }
}
