openapi: 3.0.1
info:
  title: payment-v1
  description: |
    Servicio web de propósito general, responsable de recibir las facturas y procesar sus pagos.
  version: v1
servers:
  - url: http://localhost:8015/poc/business/payment/v1
paths:
  /payments:
    get:
      summary: Obtiene todos los pagos realizados por cliente.
      operationId: sendToPay
      parameters:
        - $ref: '#/components/parameters/HeaderTraceId'
        - $ref: '#/components/parameters/QueryParamDocumentType'
        - $ref: '#/components/parameters/QueryParamDocumentNumber'
      responses:
        200:
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentResponse'

        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'

components:

  parameters:
    HeaderTraceId:
      in: header
      name: trace-id
      description: Identificador único de la petición.
      schema:
        type: string
        example: 3f2504e0-4f89-11e9-9107-d9e11d295109
      required: true

    QueryParamDocumentType:
      in: query
      name: documentType
      description: Tipo de documento del cliente (DNI, PASSPORT).
      schema:
        type: string
        example: DNI
      required: true

    QueryParamDocumentNumber:
      in: query
      name: documentNumber
      description: Número de documento del cliente.
      schema:
        type: string
        example: 76518038
      required: true

  schemas:
    PaymentResponse:
      type: object
      properties:
        invoiceId:
          type: number
          description: ID del registro de la factura.
          example: 1
        total:
          type: number
          description: Monto total de la venta
          example: 39.9

    ApiException:
      type: object
      properties:
        type:
          type: string
          description: Tipo de error
          example: /errors/no-data
        code:
          type: string
          description: Código de error
          example: Default
        message:
          type: string
          description: Mensaje de error
          example: Product not found