{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}-hpa
  labels:
    app: {{ .Values.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- range .Values.hpa.metrics }}
    - type: {{ .type }}
      resource:
        name: {{ .resource.name }}
        target:
          type: {{ .resource.target.type }}
          averageUtilization: {{ .resource.target.averageUtilization }}
    {{- end }}
  {{- end }}