{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: "{{ $value | b64enc }}"
    {{- end }}
  {{- end }}
---