name: mongo-db

container:
  image:
    repository: mongo
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 27017
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"

secrets:
  MONGO_INITDB_ROOT_USERNAME: "poc-user"
  MONGO_INITDB_ROOT_PASSWORD: "qwerty"
  MONGO_INITDB_DATABASE: "tablePlacement"

service:
  nodePort: 30717

deployment:
  replicas: 1

hpa:
  enabled: false

initdb:
  value: initdb.js

namespace: restaurant
helmTemplate: database
clusterIP: 10.96.1.2

docker:
  hostPort: 27017
  dependencies: none
  volumes: ./../../backend/database/mongo-db:/docker-entrypoint-initdb.d;./../../backend/database/mongo-db/data:/data