name: postgres-db

container:
  image:
    repository: postgres
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 5432
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"

secrets:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "qwerty"

service:
  nodePort: 30032

deployment:
  replicas: 1

hpa:
  enabled: false

initdb:
  value: initdb.sh

namespace: restaurant
helmTemplate: database
clusterIP: 10.96.1.4

docker:
  hostPort: 5432
  dependencies: none
  volumes: ./../../backend/database/postgres-db:/docker-entrypoint-initdb.d;./../../backend/database/postgres-db/data:/data