pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                script {
                    def mvnCmd = 'mvn clean package'
                    def mvnOutput = sh(script: mvnCmd, returnStdout: true).trim()
                    if (mvnOutput.contains('BUILD SUCCESS')) {
                        echo 'Maven build successful'
                    } else {
                        error 'Maven build failed'
                    }
                }
            }
        }
        stage('Deploy') {
          steps {
            withCredentials(bindings: [ string(credentialsId: 'k8s-cluster-token', variable: 'api_token') ]) {
                sh 'kubectl apply -f devops/k8s/manifests/auth-adapter-v1/ --server https://f247-179-6-212-27.ngrok-free.app --token $api_token --insecure-skip-tls-verify=true'
            }
          }
        }
    }
}
