configuration:
  project-type: BFF

  logging:
    logging-type:
      error: true
      rest.server.req: false
      rest.server.res: false
      rest.client.req: true
      rest.client.res: true
    obfuscation:
      body-fields: [ ]
      headers: [ ]

  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  rest-clients:
    menu-v1:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: http://${MENU_V1_DOMAIN:localhost:8012}/poc/business/menu/v1/
        headers:
          provided:
            Accept: application/json
          generated:
            parent-id: PARENT_ID
            timestamp: TIMESTAMP
          forwarded:
            trace-id: trace-id
            channel-id: channel-id
    menu-v2:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: http://${MENU_V2_DOMAIN:localhost:8016}/poc/business/menu/v2/
        headers:
          provided:
            Accept: application/x-ndjson, application/json
          generated:
            parent-id: PARENT_ID
            timestamp: TIMESTAMP
          forwarded:
            trace-id: trace-id
            channel-id: channel-id
    table-placement-v1:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: http://${TABLE_PLACEMENT_DOMAIN:localhost:8013}/poc/business/table-placement/v1/
        headers:
          provided:
            Accept: application/x-ndjson, application/json
          generated:
            parent-id: PARENT_ID
            timestamp: TIMESTAMP
          forwarded:
            trace-id: trace-id
            channel-id: channel-id
    invoice-v1:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: http://${INVOICE_DOMAIN:localhost:8014}/poc/business/invoice/v1/
        headers:
          provided:
            Accept: application/x-ndjson, application/json
          generated:
            parent-id: PARENT_ID
            timestamp: TIMESTAMP
          forwarded:
            trace-id: trace-id
            channel-id: channel-id

  menu-info:
    selector-class: ${MENU_REPOSITORY_SELECTOR:com.demo.poc.entrypoint.menu.repository.MenuV1Repository}