configuration:
  project-type: MS

  logging:
    obfuscation:
      body-fields: [ ]
      headers: [ ]

  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  rules:
    directory: rules/
    strategies:
      DiscountRule: discount_rules.drl