name: redis-server

container:
  image:
    repository: redis
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 6379
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"

service:
  nodePort: 30379

deployment:
  replicas: 1

hpa:
  enabled: false

namespace: restaurant
helmTemplate: default

docker:
  hostPort: 6379
  dependencies: none
  volumes: none