server:
  port: ${SERVER_PORT:8020}
  mock-port: ${MOCK_PORT:8021}

spring:
  application:
    name: mock-service-v1
  profiles:
    active: ${PROFILE:dev}
  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true
  reactor:
    debug-agent:
      enabled: true

# actuator endpoints
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans, env, loggers, flyway
  endpoint:
    health:
      show-details: always
      probes: #livess & readiness probe
        enabled: true

# Performance Spring
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:ERROR}