name: invoice-v1
image:
  repository: miguelarmasabt/invoice
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8014
  nodePort: 30014
replicas: 1

configMaps:
  KAFKA_DOMAIN: "kafka-server:9093"
  POSTGRESQL_DOMAIN: "postgres-db:5432"
  POSTGRESQL_USERNAME: "poc_user"
  PRODUCT_DOMAIN: "product-v1:8017"
  CONFIG_SERVER_DOMAIN: "config-server-v1:8888"
  JAVA_OPTS: "-Xms256M -Xmx256M"

secrets:
  POSTGRESQL_PASSWORD: "qwerty"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8014
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8014
  initialDelaySeconds: 60
  periodSeconds: 30

namespace: restaurant
helmTemplate: with-health

docker:
  hostPort: 8014
  dependencies: config-server-v1;postgres-db;kafka-server
  volumes: none