pipeline {
    agent any
    stages {
        stage('Deploy') {
            steps {
                withCredentials(bindings: [ string(credentialsId: 'k8s-cluster-token', variable: 'api_token') ]) {
                    sh 'kubectl apply -f devops/k8s/manifests/keycloak-server/ --server https://e1bd-2800-200-ed50-2d5-51f4-16f6-f21f-a5f9.ngrok-free.app --token $api_token --insecure-skip-tls-verify=true'
                }
            }
        }
    }
}
