server:
  port: ":8017"
  corsOrigins:
    - http://localhost:63342

projectType: MS

logging:
  loggingType:
    rest-server-req: false
    rest-server-res: false

errorMessages:
  Default: "No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente."

database:
  user: poc_user
  password: qwerty
  host: 127.0.0.1:3306
  name: db_products