package restclient

import "com.demo.poc/commons/tracing"

type RestClient struct {
	Request RequestTemplate                    `mapstructure:"request"`
	Errors  map[string]RestClientErrorTemplate `mapstructure:"errors"`
}

type RequestTemplate struct {
	Endpoint string            `mapstructure:"endpoint"`
	Headers  HeaderTemplate    `mapstructure:"headers"`
	FormData map[string]string `mapstructure:"formData"`
}

type HeaderTemplate struct {
	Provided      map[string]string                     `mapstructure:"provided"`
	Forwarded     map[string]string                     `mapstructure:"forwarded"`
	AutoGenerated map[string]tracing.AutoGeneratedParam `mapstructure:"autoGenerated"`
	Tracing       map[string]string                     `mapstructure:"tracing"`
}

type RestClientErrorTemplate struct {
	CustomCode string `mapstructure:"customCode"`
	Message    string `mapstructure:"message"`
	HttpCode   int    `mapstructure:"httpCode"`
}
