apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
  labels:
    type: local
    app: {{ .Values.name }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/"