// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"com.demo.poc/cmd/commons/custom/config"
	"com.demo.poc/cmd/entrypoint/products/repository"
	"com.demo.poc/cmd/entrypoint/products/rest"
	"com.demo.poc/cmd/entrypoint/products/service"
	"github.com/gin-gonic/gin"
)

// Injectors from dependency_injection.go:

func Rest() *gin.Engine {
	db := config.GormDB()
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productRestService := rest.NewProductRestService(productService)
	engine := rest.SetupRouter(productRestService)
	return engine
}
