---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-v1-config-map
data:
    AUTH_ADAPTER_DOMAIN: "auth-adapter-v1:8011"
    ENABLE_AUTH: "true"
    JAVA_OPTS: "-Xms256M -Xmx256M"
    ORDER_HUB_DOMAIN: "order-hub-v1:8018"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-v1
  labels:
    app: api-gateway-v1
spec:
  type: NodePort
  selector:
    app: api-gateway-v1
  ipFamilies:
    - IPv4
  ports:
    - name: api-gateway-v1
      port: 8010
      nodePort: 30010
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v1
  labels:
    app: api-gateway-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-v1
  template:
    metadata:
      labels:
        app: api-gateway-v1
    spec:
      containers:
        - name: api-gateway-v1
          image: "miguelarmasabt/api-gateway:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8010

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8010
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8010
            initialDelaySeconds: 60
            periodSeconds: 30

          env:
              - name: AUTH_ADAPTER_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: AUTH_ADAPTER_DOMAIN
              - name: ENABLE_AUTH
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: ENABLE_AUTH
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: JAVA_OPTS
              - name: ORDER_HUB_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: ORDER_HUB_DOMAIN
---
# Source: generic-backend-chart/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-v1-hpa
  labels:
    app: api-gateway-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
