---
# Source: generic-backend-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: invoice-v1-secret
type: Opaque
data:
    POSTGRESQL_PASSWORD: "cXdlcnR5"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-v1-config-map
data:
    CONFIG_SERVER_DOMAIN: "config-server-v1:8888"
    JAVA_OPTS: "-Xms256M -Xmx256M"
    KAFKA_DOMAIN: "kafka-server:9093"
    POSTGRESQL_DOMAIN: "postgres-db:5432"
    POSTGRESQL_USERNAME: "poc_user"
    PRODUCT_DOMAIN: "product-v1:8017"
    RULES_PROCESSOR_DOMAIN: "rules-processor-v1:8019"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: invoice-v1
  labels:
    app: invoice-v1
spec:
  type: NodePort
  selector:
    app: invoice-v1
  ipFamilies:
    - IPv4
  ports:
    - name: invoice-v1
      port: 8014
      nodePort: 30014
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-v1
  labels:
    app: invoice-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-v1
  template:
    metadata:
      labels:
        app: invoice-v1
    spec:
      containers:
        - name: invoice-v1
          image: "miguelarmasabt/invoice:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8014

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8014
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8014
            initialDelaySeconds: 60
            periodSeconds: 30

          env:
              - name: CONFIG_SERVER_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: invoice-v1-config-map
                    key: CONFIG_SERVER_DOMAIN
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: invoice-v1-config-map
                    key: JAVA_OPTS
              - name: KAFKA_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: invoice-v1-config-map
                    key: KAFKA_DOMAIN
              - name: POSTGRESQL_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: invoice-v1-config-map
                    key: POSTGRESQL_DOMAIN
              - name: POSTGRESQL_USERNAME
                valueFrom:
                  configMapKeyRef:
                    name: invoice-v1-config-map
                    key: POSTGRESQL_USERNAME
              - name: PRODUCT_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: invoice-v1-config-map
                    key: PRODUCT_DOMAIN
              - name: RULES_PROCESSOR_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: invoice-v1-config-map
                    key: RULES_PROCESSOR_DOMAIN
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: invoice-v1-secret
                    key: POSTGRESQL_PASSWORD
