---
# Source: generic-server-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-server-config-map
data:
    KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-server:9093,EXTERNAL://-127.0.0.1:9092,DOCKER://host.docker.internal:29092"
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"
    KAFKA_BROKER_ID: "1"
    KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    KAFKA_JMX_HOSTNAME: "127.0.0.1"
    KAFKA_JMX_PORT: "9999"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT"
    KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
---
# Source: generic-server-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  labels:
    app: kafka-server
spec:
  type: NodePort
  selector:
    app: kafka-server
  ipFamilies:
    - IPv4
  ports:
    - name: kafka-server
      port: 9092
      nodePort: 30092
---
# Source: generic-server-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-server
  labels:
    app: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-server
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      containers:
        - name: kafka-server
          image: "confluentinc/cp-kafka:7.3.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          env:
              - name: KAFKA_ADVERTISED_LISTENERS
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_ADVERTISED_LISTENERS
              - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              - name: KAFKA_AUTHORIZER_CLASS_NAME
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_AUTHORIZER_CLASS_NAME
              - name: KAFKA_BROKER_ID
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_BROKER_ID
              - name: KAFKA_INTER_BROKER_LISTENER_NAME
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_INTER_BROKER_LISTENER_NAME
              - name: KAFKA_JMX_HOSTNAME
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_JMX_HOSTNAME
              - name: KAFKA_JMX_PORT
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_JMX_PORT
              - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              - name: KAFKA_LOG4J_LOGGERS
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_LOG4J_LOGGERS
              - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              - name: KAFKA_ZOOKEEPER_CONNECT
                valueFrom:
                  configMapKeyRef:
                    name: kafka-server-config-map
                    key: KAFKA_ZOOKEEPER_CONNECT
