---
# Source: generic-server-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-server-config-map
data:
    ZOOKEEPER_CLIENT_PORT: "2181"
    ZOOKEEPER_SERVERS: "zookeeper-server:2888:3888"
    ZOOKEEPER_SERVER_ID: "1"
---
# Source: generic-server-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-server
  labels:
    app: zookeeper-server
spec:
  type: NodePort
  selector:
    app: zookeeper-server
  ipFamilies:
    - IPv4
  ports:
    - name: zookeeper-server
      port: 2181
      nodePort: 30181
---
# Source: generic-server-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-server
  labels:
    app: zookeeper-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-server
  template:
    metadata:
      labels:
        app: zookeeper-server
    spec:
      containers:
        - name: zookeeper-server
          image: "confluentinc/cp-zookeeper:7.3.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          env:
              - name: ZOOKEEPER_CLIENT_PORT
                valueFrom:
                  configMapKeyRef:
                    name: zookeeper-server-config-map
                    key: ZOOKEEPER_CLIENT_PORT
              - name: ZOOKEEPER_SERVERS
                valueFrom:
                  configMapKeyRef:
                    name: zookeeper-server-config-map
                    key: ZOOKEEPER_SERVERS
              - name: ZOOKEEPER_SERVER_ID
                valueFrom:
                  configMapKeyRef:
                    name: zookeeper-server-config-map
                    key: ZOOKEEPER_SERVER_ID
