name: mysql-db

container:
  image:
    repository: mysql
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 3306
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"

configMaps:
  TZ: "UTC"

secrets:
  MYSQL_ROOT_PASSWORD: "qwerty"

service:
  nodePort: 30006

deployment:
  replicas: 1

hpa:
  enabled: false

initdb:
  value: initdb.sql

namespace: restaurant
helmTemplate: database
clusterIP: 10.96.1.3

docker:
  hostPort: 3306
  dependencies: none
  volumes: ./../../backend/database/mysql-db:/docker-entrypoint-initdb.d;./../../backend/database/mysql-db/data:/data