name: mysql-db
image:
  repository: mysql
  tag: "latest"
  pullPolicy: IfNotPresent
ports:
  containerPort: 3306
  nodePort: 30006
replicas: 1

configMaps:
  TZ: "UTC"

secrets:
  MYSQL_ROOT_PASSWORD: "qwerty"

initdb:
  value: initdb.sql

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

namespace: restaurant
helmTemplate: database
clusterIP: 10.96.1.3

docker:
  hostPort: 3306
  dependencies: none
  volumes: ./../application/backend/database/mysql-db:/docker-entrypoint-initdb.d;./../application/backend/database/mysql-db/data:/data