apiVersion: v2
name: generic-database-chart
description: A generic Helm chart for deploying Kubernetes database with dynamic ConfigMaps, Secrets, and Deployments.
type: application
version: 0.1.0
appVersion: "1.0.0"