version: '3.1'

services:
@services
networks:
  dev_environment:
    driver: bridge
    #activate ipv6
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    #IP Adress Manager
    ipam:
      driver: default
      config:
        - subnet: 172.16.232.0/24
          gateway: 172.16.232.1
        - subnet: "2001:3974:3979::/64"
          gateway: "2001:3974:3979::1"