name: kafka-server
image:
  repository: confluentinc/cp-kafka
  tag: "7.3.2"
  pullPolicy: IfNotPresent
ports:
  containerPort: 9092
  nodePort: 30092
replicas: 1

configMaps:
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-server:9093,EXTERNAL://-127.0.0.1:9092,DOCKER://host.docker.internal:29092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
  KAFKA_BROKER_ID: "1"
  KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_JMX_PORT: "9999"
  KAFKA_JMX_HOSTNAME: "127.0.0.1"
  KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

namespace: restaurant
helmTemplate: default

docker:
  hostPort: 9092
  dependencies: zookeeper-server
  volumes: none